# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timezone', models.CharField(max_length=20)),
                ('metro_code', models.IntegerField(default=0)),
                ('region_code', models.CharField(max_length=10)),
                ('region_name', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=10)),
                ('zip_code', models.CharField(max_length=10)),
                ('country_name', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
    ]
