# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('readalert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
