# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readalert', '0002_people_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='is_safehouse',
            field=models.BigIntegerField(default=0),
        ),
    ]
